# Generated by Django 4.2.1 on 2023-06-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=50)),
                ('topico', models.CharField(max_length=100)),
                ('problematica', models.TextField()),
            ],
        ),
    ]
